### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by lengyu1983** [roothide/Developer#8]
Hello, I have encountered some issues.
In the rootless, if I write code like this
%ctor{
NSString *str = [aaaa bbb];
if([str isequaltostring:@"xxxxxx"]{
%init(group)
}
}
This code runs normally. But the same code cannot work properly under roothide, it must be written like this
%ctor{
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
NSString *str = [aaaa bbb];
if([str isequaltostring:@"xxxxxx"]{
%init(group)
}
});
}
This way, we can read how NSString * str executes the plugin group normally,
Can it be solved? Because I have many rootless debs like this, I don't want to recompile them all.

**Comment by roothider** [comment]
I think this has something to do with your implementation of "[aaaa bbb]"

**Comment by roothider** [comment]
theos and Logos and MobileSubstrate all work perfectly on roothide, this issue should be a special case of yours, it depends on how your tweak is implemented, the roothide environment is indeed a little different from the rootless environment.

**Comment by lengyu1983** [comment]
> theos and Logos and MobileSubstrate all work perfectly on roothide, this issue should be a special case of yours, it depends on how your tweak is implemented, the roothide environment is indeed a little different from the rootless environment.

Let me put it this way, in Roothide,%ctor{} must delay to read the str returned by [aaa bbbb]. Not delaying will return null, delaying for one second can return str normally.

**Comment by lengyu1983** [comment]
> I think this has something to do with your implementation of "[aaaa bbb]"
> 
> 

[aaaa bbb]is return a NSString *str。

**Comment by roothider** [comment]
> > I think this has something to do with your implementation of "[aaaa bbb]"
> 
> [aaaa bbb]is return a NSString *str。

how does [aaa bbbb] implement? 
If it just returns a @"constant string" immediately or uses [NSString init] immediately it's impossible to return nil

**Comment by lengyu1983** [comment]
> > > I think this has something to do with your implementation of "[aaaa bbb]"
> 
> > 
> 
> > [aaaa bbb]is return a NSString *str。
> 
> 
> 
> how does [aaa bbbb] implement? 
> 
> If it just returns a @"constant string" immediately or uses [NSString init] immediately it's impossible to return nil

like this
@implementation aaaa
+ (NSString *)bbb {
    return @"Hello";
}
@end

//in tweaks
%ctor {
NSString *str = [aaaa bbb];
NSLog(@"11111=====%@",str);
//rootless or rootfull
//Normal operation, print return value
//11111=====Hello
}
//roothide
//11111=====(null)
//if User GCD roothide
%ctor {
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
NSString *str = [aaaa bbb];
NSLog(@"11111=====%@",str);
//11111=====Hello
 });
}

**Comment by roothider** [comment]
> > > > I think this has something to do with your implementation of "[aaaa bbb]"
> > 
> > 
> > > 
> > 
> > 
> > > [aaaa bbb]is return a NSString *str。
> > 
> > 
> > how does [aaa bbbb] implement?
> > If it just returns a @"constant string" immediately or uses [NSString init] immediately it's impossible to return nil
> 
> like this @implementation aaaa
> 
> * (NSString *)bbb {
>   return @"Hello";
>   }
>   @EnD
> 
> //in tweaks %ctor { NSString *str = [aaaa bbb]; NSLog(@"11111=====%@",str); //rootless or rootfull //Normal operation, print return value //11111=====Hello } //roothide //11111=====(null) //if User GCD roothide %ctor { dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{ NSString *str = [aaaa bbb]; NSLog(@"11111=====%@",str); //11111=====Hello }); }

I guess your tweak may conflict with other tweaks. can you send me a example(a deb or theos project) to reproduce this issue?
and whats your device and ios version and what version of roothide Bootstrap/Dopamine you're using?

**Comment by lengyu1983** [comment]
> > > > > I think this has something to do with your implementation of "[aaaa bbb]"
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > [aaaa bbb]is return a NSString *str。
> > > 
> > > 
> > > how does [aaa bbbb] implement?
> > > If it just returns a @"constant string" immediately or uses [NSString init] immediately it's impossible to return nil
> > 
> > 
> > like this @implementation aaaa
> > 
> > * (NSString *)bbb {
> >   return @"Hello";
> >   }
> >   @EnD
> > 
> > //in tweaks %ctor { NSString *str = [aaaa bbb]; NSLog(@"11111=====%@",str); //rootless or rootfull //Normal operation, print return value //11111=====Hello } //roothide //11111=====(null) //if User GCD roothide %ctor { dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{ NSString *str = [aaaa bbb]; NSLog(@"11111=====%@",str); //11111=====Hello }); }
> 
> that shouldn't happen, I guess your tweak may conflict with other tweaks. can you send me a example(a deb or theos project) to reproduce this issue? and whats your device and ios version and what version of roothide Bootstrap/Dopamine you're using?

I am user 15.4.1/16.0.1 two device with Dopamine2-roothide newest version.
[test.zip](https://github.com/user-attachments/files/17442807/test.zip)

**Comment by roothider** [comment]
<img width="788" alt="image" src="https://github.com/user-attachments/assets/0d202915-f388-409f-9ce8-65a4de2134a8">

**Comment by lengyu1983** [comment]
> <img width="788" alt="image" src="https://github.com/user-attachments/assets/0d202915-f388-409f-9ce8-65a4de2134a8">
> 
> 
try this way
%ctor {
NSString *str = [AAAA BBB];
NSLog(@"11111=====%@",str);
}

**Comment by roothider** [comment]
<img width="810" alt="image" src="https://github.com/user-attachments/assets/1c2497cf-8e66-40b8-b8a9-dddb2cf14ece">
<img width="387" alt="image" src="https://github.com/user-attachments/assets/3cefef21-f82e-48f4-9219-36204aa4a4aa">
